// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {"projectId":"devils-access-a7a51","appId":"1:380482260656:web:1352e3794578b8743a695e","apiKey":"AIzaSyA27K7jEdaE9yM09N63rzu3T22sB3r4m5g","authDomain":"devils-access-a7a51.firebaseapp.com","storageBucket":"devils-access-a7a51.appspot.com"};
